# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec9dbc4914dbf99d48343281c66542c0f05612c9e26ec35cd7db02dbf672a4aa9a1fef30f06e4e7dd9f6ed500e62375e8d90ffa7497ae988b238a85c3e29023

test:
  secret_key_base: 40c4ff58592e08988d18d4b65564f38f69e8c9792abea8b4147fda108b5b724f4e27f002f11ac504260c488356aa4539dba608df88e08737822a8225dff7c65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
